services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/RestaurantCoursework
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - APP_JWT_SECRET=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
      - APP_JWT_EXPIRATION_MILLISECONDS=604800000
    networks:
      - spring-postgres

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=RestaurantCoursework
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres

volumes:
  postgres-data:

networks:
  spring-postgres:
    driver: bridge